<?php

require_once(dirname(__FILE__)."\..\..\..\app\models\user.php");


class ModelMock extends Model{
	const table_name = "";
	const fields_names = "id,email,password,nickname,created_datetime";
	
	public static function __construct_fill_fields($fields_values){
		parent::__construct_fill_fields($fields_values);
	}
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-08 at 21:08:53.
 */
class ModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new ModelMock();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Model::find
     * @todo   Implement testFind().
     */
    public function testFind() {
	$attr =  array(
  	    'id' => 1,
  	    'email' => 'a@a.fr',
  	    'password' => 'azraaefaefa',
  	    'nickname' => 'toto',
  	    'created' => '2014-01-02'
  	);
        
        //$this->object = new ModelMock();

        $stub = $this->getMockBuilder('Model')
                     ->disableOriginalConstructor()
                     ->getMock();

        // Configure the stub.
        $stub->expects($this->any())
             ->method('execute')
             ->will($this->returnValue(array(0 => $attr)));
        
	$result = (new ModelMock())->find(1);
	
	echo "prout";
	echo var_dump($result);
	
         $this->assertEquals($result->get_fields_values(), $attr);
        
    }

    /**
     * @covers Model::save
     * @todo   Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model::get_attr
     * @todo   Implement testGet_attr().
     */
    public function testGet_attr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model::set_attr
     * @todo   Implement testSet_attr().
     */
    public function testSet_attr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
